### ISSUE TITLE
Excessive download times?

### ISSUE THREAD

**Issue by znmeb** [kwartler/ODSC#1]
I'm trying to run <https://github.com/kwartler/ODSC/blob/master/0_Setup.R> on my Linux system and it's taking a really long time. This is an 8-core 4 GHz workstation with an 80 Mbit/second wired connection.

It looks like you're installing the "Suggested" packages for all the libraries in "libs". Do you really need all of those?

**Comment by kwartler** [comment]
It does take a while.  My usual default is to get suggested, but considering your input probably should remove it.  Will take a quick look.

**Comment by kwartler** [comment]
thx for the assist.
